{
 "cells": [
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 1,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 2,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Cliente</th>\n",
       "      <th>Satisfação</th>\n",
       "      <th>Tempo de Espera (min)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Naruto</td>\n",
       "      <td>Alta</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Goku</td>\n",
       "      <td>Alta</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Vegeta</td>\n",
       "      <td>Média</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Sasuke</td>\n",
       "      <td>Alta</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Madara</td>\n",
       "      <td>Média</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Luffy</td>\n",
       "      <td>Baixa</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Zoro</td>\n",
       "      <td>Alta</td>\n",
       "      <td>22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Sanji</td>\n",
       "      <td>Baixa</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Yusuke</td>\n",
       "      <td>Baixa</td>\n",
       "      <td>14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Kurama</td>\n",
       "      <td>Média</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Gon</td>\n",
       "      <td>Média</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Eren</td>\n",
       "      <td>Média</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Mikasa</td>\n",
       "      <td>Alta</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Light</td>\n",
       "      <td>Alta</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>L</td>\n",
       "      <td>Alta</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Peter Parker</td>\n",
       "      <td>Baixa</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Bruce Wayne</td>\n",
       "      <td>Alta</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Thanos</td>\n",
       "      <td>Média</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Edmundo</td>\n",
       "      <td>Baixa</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Vegetti</td>\n",
       "      <td>Média</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Cliente Satisfação  Tempo de Espera (min)\n",
       "0         Naruto       Alta                      8\n",
       "1           Goku       Alta                     10\n",
       "2         Vegeta      Média                     17\n",
       "3         Sasuke       Alta                      8\n",
       "4         Madara      Média                     15\n",
       "5          Luffy      Baixa                      5\n",
       "6           Zoro       Alta                     22\n",
       "7          Sanji      Baixa                     26\n",
       "8         Yusuke      Baixa                     14\n",
       "9         Kurama      Média                      8\n",
       "10           Gon      Média                     12\n",
       "11          Eren      Média                     28\n",
       "12        Mikasa       Alta                      6\n",
       "13         Light       Alta                     10\n",
       "14             L       Alta                     19\n",
       "15  Peter Parker      Baixa                     21\n",
       "16   Bruce Wayne       Alta                     18\n",
       "17        Thanos      Média                     19\n",
       "18       Edmundo      Baixa                     13\n",
       "19       Vegetti      Média                     19"
      ]
     },
<<<<<<< HEAD
     "execution_count": 2,
=======
     "execution_count": 5,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('pesquisa_satisfacao.csv', sep=';')\n"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 3,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Satisfação</th>\n",
       "      <th>Tempo de Espera (min)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Alta</td>\n",
       "      <td>12.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Baixa</td>\n",
       "      <td>15.80</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Média</td>\n",
       "      <td>16.86</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Satisfação  Tempo de Espera (min)\n",
       "0       Alta                  12.62\n",
       "1      Baixa                  15.80\n",
       "2      Média                  16.86"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "media_satisfacao = df.groupby ('Satisfação') ['Tempo de Espera (min)'].mean().reset_index()\n",
    "media_satisfacao['Tempo de Espera (min)'] = round (media_satisfacao['Tempo de Espera (min)'], 2)\n",
    "media_satisfacao"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 4,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\luiz.gutemberg\\AppData\\Local\\Temp\\ipykernel_13724\\3435742200.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  df_anp = pd.read_csv('ANP2025.csv', sep=';')\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Regiao - Sigla</th>\n",
       "      <th>Estado - Sigla</th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Revenda</th>\n",
       "      <th>CNPJ da Revenda</th>\n",
       "      <th>Nome da Rua</th>\n",
       "      <th>Numero Rua</th>\n",
       "      <th>Complemento</th>\n",
       "      <th>Bairro</th>\n",
       "      <th>Cep</th>\n",
       "      <th>Produto</th>\n",
       "      <th>Data da Coleta</th>\n",
       "      <th>Valor de Venda</th>\n",
       "      <th>Valor de Compra</th>\n",
       "      <th>Unidade de Medida</th>\n",
       "      <th>Bandeira</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>NE</td>\n",
       "      <td>CE</td>\n",
       "      <td>SOBRAL</td>\n",
       "      <td>ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...</td>\n",
       "      <td>08.775.979/0002-62</td>\n",
       "      <td>RUA TABELIÃO IDELFONSO CAVALCANTI</td>\n",
       "      <td>455</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>62010-000</td>\n",
       "      <td>GASOLINA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>NE</td>\n",
       "      <td>CE</td>\n",
       "      <td>SOBRAL</td>\n",
       "      <td>ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...</td>\n",
       "      <td>08.775.979/0002-62</td>\n",
       "      <td>RUA TABELIÃO IDELFONSO CAVALCANTI</td>\n",
       "      <td>455</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>62010-000</td>\n",
       "      <td>GASOLINA ADITIVADA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>NE</td>\n",
       "      <td>CE</td>\n",
       "      <td>SOBRAL</td>\n",
       "      <td>ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...</td>\n",
       "      <td>08.775.979/0002-62</td>\n",
       "      <td>RUA TABELIÃO IDELFONSO CAVALCANTI</td>\n",
       "      <td>455</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>62010-000</td>\n",
       "      <td>DIESEL S10</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,19</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>NE</td>\n",
       "      <td>CE</td>\n",
       "      <td>SOBRAL</td>\n",
       "      <td>ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...</td>\n",
       "      <td>08.775.979/0002-62</td>\n",
       "      <td>RUA TABELIÃO IDELFONSO CAVALCANTI</td>\n",
       "      <td>455</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>62010-000</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>5,19</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>NE</td>\n",
       "      <td>CE</td>\n",
       "      <td>SOBRAL</td>\n",
       "      <td>V.C.EMPREENDIMENTOS LTDA</td>\n",
       "      <td>03.551.935/0002-35</td>\n",
       "      <td>AVENIDA JOSE EUCLIDES FERREIRA GOMES</td>\n",
       "      <td>30</td>\n",
       "      <td>POSTO FLASH</td>\n",
       "      <td>CORACAO DE JESUS</td>\n",
       "      <td>62043-070</td>\n",
       "      <td>GASOLINA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,53</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>429518</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>429519</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>429520</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>429521</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>429522</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>429523 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       Regiao - Sigla Estado - Sigla Municipio  \\\n",
       "0                  NE             CE    SOBRAL   \n",
       "1                  NE             CE    SOBRAL   \n",
       "2                  NE             CE    SOBRAL   \n",
       "3                  NE             CE    SOBRAL   \n",
       "4                  NE             CE    SOBRAL   \n",
       "...               ...            ...       ...   \n",
       "429518            NaN            NaN       NaN   \n",
       "429519            NaN            NaN       NaN   \n",
       "429520            NaN            NaN       NaN   \n",
       "429521            NaN            NaN       NaN   \n",
       "429522            NaN            NaN       NaN   \n",
       "\n",
       "                                                  Revenda  \\\n",
       "0       ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...   \n",
       "1       ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...   \n",
       "2       ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...   \n",
       "3       ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...   \n",
       "4                                V.C.EMPREENDIMENTOS LTDA   \n",
       "...                                                   ...   \n",
       "429518                                                NaN   \n",
       "429519                                                NaN   \n",
       "429520                                                NaN   \n",
       "429521                                                NaN   \n",
       "429522                                                NaN   \n",
       "\n",
       "            CNPJ da Revenda                           Nome da Rua Numero Rua  \\\n",
       "0        08.775.979/0002-62     RUA TABELIÃO IDELFONSO CAVALCANTI        455   \n",
       "1        08.775.979/0002-62     RUA TABELIÃO IDELFONSO CAVALCANTI        455   \n",
       "2        08.775.979/0002-62     RUA TABELIÃO IDELFONSO CAVALCANTI        455   \n",
       "3        08.775.979/0002-62     RUA TABELIÃO IDELFONSO CAVALCANTI        455   \n",
       "4        03.551.935/0002-35  AVENIDA JOSE EUCLIDES FERREIRA GOMES         30   \n",
       "...                     ...                                   ...        ...   \n",
       "429518                  NaN                                   NaN        NaN   \n",
       "429519                  NaN                                   NaN        NaN   \n",
       "429520                  NaN                                   NaN        NaN   \n",
       "429521                  NaN                                   NaN        NaN   \n",
       "429522                  NaN                                   NaN        NaN   \n",
       "\n",
       "        Complemento            Bairro        Cep             Produto  \\\n",
       "0               NaN            CENTRO  62010-000            GASOLINA   \n",
       "1               NaN            CENTRO  62010-000  GASOLINA ADITIVADA   \n",
       "2               NaN            CENTRO  62010-000          DIESEL S10   \n",
       "3               NaN            CENTRO  62010-000              ETANOL   \n",
       "4       POSTO FLASH  CORACAO DE JESUS  62043-070            GASOLINA   \n",
       "...             ...               ...        ...                 ...   \n",
       "429518          NaN               NaN        NaN                 NaN   \n",
       "429519          NaN               NaN        NaN                 NaN   \n",
       "429520          NaN               NaN        NaN                 NaN   \n",
       "429521          NaN               NaN        NaN                 NaN   \n",
       "429522          NaN               NaN        NaN                 NaN   \n",
       "\n",
       "       Data da Coleta Valor de Venda  Valor de Compra Unidade de Medida  \\\n",
       "0          01/01/2025           6,29              NaN        R$ / litro   \n",
       "1          01/01/2025           6,49              NaN        R$ / litro   \n",
       "2          01/01/2025           6,19              NaN        R$ / litro   \n",
       "3          01/01/2025           5,19              NaN        R$ / litro   \n",
       "4          01/01/2025           6,53              NaN        R$ / litro   \n",
       "...               ...            ...              ...               ...   \n",
       "429518            NaN            NaN              NaN               NaN   \n",
       "429519            NaN            NaN              NaN               NaN   \n",
       "429520            NaN            NaN              NaN               NaN   \n",
       "429521            NaN            NaN              NaN               NaN   \n",
       "429522            NaN            NaN              NaN               NaN   \n",
       "\n",
       "       Bandeira  \n",
       "0        RAIZEN  \n",
       "1        RAIZEN  \n",
       "2        RAIZEN  \n",
       "3        RAIZEN  \n",
       "4        RAIZEN  \n",
       "...         ...  \n",
       "429518      NaN  \n",
       "429519      NaN  \n",
       "429520      NaN  \n",
       "429521      NaN  \n",
       "429522      NaN  \n",
       "\n",
       "[429523 rows x 16 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_anp = pd.read_csv('ANP2025.csv', sep=';')\n",
    "df_anp"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 5,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Regiao - Sigla</th>\n",
       "      <th>Estado - Sigla</th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Revenda</th>\n",
       "      <th>CNPJ da Revenda</th>\n",
       "      <th>Nome da Rua</th>\n",
       "      <th>Numero Rua</th>\n",
       "      <th>Complemento</th>\n",
       "      <th>Bairro</th>\n",
       "      <th>Cep</th>\n",
       "      <th>Produto</th>\n",
       "      <th>Data da Coleta</th>\n",
       "      <th>Valor de Venda</th>\n",
       "      <th>Valor de Compra</th>\n",
       "      <th>Unidade de Medida</th>\n",
       "      <th>Bandeira</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>54</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>CAMPOS DOS GOYTACAZES</td>\n",
       "      <td>POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA</td>\n",
       "      <td>31.212.889/0002-85</td>\n",
       "      <td>AVENIDA NILO PECANHA</td>\n",
       "      <td>614</td>\n",
       "      <td>/822 PATIO</td>\n",
       "      <td>PQ SANTO AMARO</td>\n",
       "      <td>28030-035</td>\n",
       "      <td>GNV</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>5,39</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / m³</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>55</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>CAMPOS DOS GOYTACAZES</td>\n",
       "      <td>POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA</td>\n",
       "      <td>31.212.889/0002-85</td>\n",
       "      <td>AVENIDA NILO PECANHA</td>\n",
       "      <td>614</td>\n",
       "      <td>/822 PATIO</td>\n",
       "      <td>PQ SANTO AMARO</td>\n",
       "      <td>28030-035</td>\n",
       "      <td>GASOLINA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>56</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>CAMPOS DOS GOYTACAZES</td>\n",
       "      <td>POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA</td>\n",
       "      <td>31.212.889/0002-85</td>\n",
       "      <td>AVENIDA NILO PECANHA</td>\n",
       "      <td>614</td>\n",
       "      <td>/822 PATIO</td>\n",
       "      <td>PQ SANTO AMARO</td>\n",
       "      <td>28030-035</td>\n",
       "      <td>GASOLINA ADITIVADA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,69</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>57</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>CAMPOS DOS GOYTACAZES</td>\n",
       "      <td>POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA</td>\n",
       "      <td>31.212.889/0002-85</td>\n",
       "      <td>AVENIDA NILO PECANHA</td>\n",
       "      <td>614</td>\n",
       "      <td>/822 PATIO</td>\n",
       "      <td>PQ SANTO AMARO</td>\n",
       "      <td>28030-035</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>4,79</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>58</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>CAMPOS DOS GOYTACAZES</td>\n",
       "      <td>POSTO DE COMBUSTIVEIS B J LTDA</td>\n",
       "      <td>06.211.735/0001-40</td>\n",
       "      <td>RUA BENEDITO QUEIROZ</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>TURF CLUB</td>\n",
       "      <td>28024-040</td>\n",
       "      <td>GASOLINA</td>\n",
       "      <td>01/01/2025</td>\n",
       "      <td>6,42</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>BRANCA</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Regiao - Sigla Estado - Sigla              Municipio  \\\n",
       "54             SE             RJ  CAMPOS DOS GOYTACAZES   \n",
       "55             SE             RJ  CAMPOS DOS GOYTACAZES   \n",
       "56             SE             RJ  CAMPOS DOS GOYTACAZES   \n",
       "57             SE             RJ  CAMPOS DOS GOYTACAZES   \n",
       "58             SE             RJ  CAMPOS DOS GOYTACAZES   \n",
       "\n",
       "                                          Revenda      CNPJ da Revenda  \\\n",
       "54  POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA   31.212.889/0002-85   \n",
       "55  POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA   31.212.889/0002-85   \n",
       "56  POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA   31.212.889/0002-85   \n",
       "57  POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA   31.212.889/0002-85   \n",
       "58                 POSTO DE COMBUSTIVEIS B J LTDA   06.211.735/0001-40   \n",
       "\n",
       "             Nome da Rua Numero Rua Complemento          Bairro        Cep  \\\n",
       "54  AVENIDA NILO PECANHA        614  /822 PATIO  PQ SANTO AMARO  28030-035   \n",
       "55  AVENIDA NILO PECANHA        614  /822 PATIO  PQ SANTO AMARO  28030-035   \n",
       "56  AVENIDA NILO PECANHA        614  /822 PATIO  PQ SANTO AMARO  28030-035   \n",
       "57  AVENIDA NILO PECANHA        614  /822 PATIO  PQ SANTO AMARO  28030-035   \n",
       "58  RUA BENEDITO QUEIROZ          1         NaN       TURF CLUB  28024-040   \n",
       "\n",
       "               Produto Data da Coleta Valor de Venda  Valor de Compra  \\\n",
       "54                 GNV     01/01/2025           5,39              NaN   \n",
       "55            GASOLINA     01/01/2025           6,49              NaN   \n",
       "56  GASOLINA ADITIVADA     01/01/2025           6,69              NaN   \n",
       "57              ETANOL     01/01/2025           4,79              NaN   \n",
       "58            GASOLINA     01/01/2025           6,42              NaN   \n",
       "\n",
       "   Unidade de Medida Bandeira  \n",
       "54           R$ / m³    VIBRA  \n",
       "55        R$ / litro    VIBRA  \n",
       "56        R$ / litro    VIBRA  \n",
       "57        R$ / litro    VIBRA  \n",
       "58        R$ / litro   BRANCA  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_anp_rj = df_anp.loc[df_anp['Estado - Sigla'] == 'RJ']\n",
    "df_anp_rj.head(5)"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 6,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\luiz.gutemberg\\AppData\\Local\\Temp\\ipykernel_13724\\3075155369.py:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)\n"
     ]
    }
   ],
   "source": [
    "df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 7,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Valor de Venda</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ANGRA DOS REIS</td>\n",
       "      <td>6.470086</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>MACAE</td>\n",
       "      <td>6.224548</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>TRES RIOS</td>\n",
       "      <td>6.206138</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>BARRA DO PIRAI</td>\n",
       "      <td>6.168793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>SAQUAREMA</td>\n",
       "      <td>6.070452</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Municipio  Valor de Venda\n",
       "0   ANGRA DOS REIS        6.470086\n",
       "10           MACAE        6.224548\n",
       "24       TRES RIOS        6.206138\n",
       "2   BARRA DO PIRAI        6.168793\n",
       "23       SAQUAREMA        6.070452"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "media_munc_rj = df_anp_rj.groupby('Municipio') ['Valor de Venda'].mean().reset_index()\n",
    "media_munc_rj = media_munc_rj.sort_values (by = 'Valor de Venda', ascending = False)\n",
    "media_munc_rj.head (5)"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 8,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [],
   "source": [
    "arry_valor_venda = np.array (media_munc_rj['Valor de Venda'])"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 9,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A média é 5.856684177816972\n",
      "A mediana é 5.891806930693069\n",
      "Primeiro quartil é (Q1)5.588252288329519\n",
      "Segundo quartil é (Q2)5.891806930693069\n",
      "Terceiro quartil é (Q3)6.047136868364782\n"
     ]
    }
   ],
   "source": [
    "media = np.mean (arry_valor_venda)\n",
    "mediana = np.median (arry_valor_venda)\n",
    "\n",
    "q1 = np.quantile (arry_valor_venda, 0.25)\n",
    "q2 = np.quantile (arry_valor_venda, 0.50)\n",
    "q3 = np.quantile (arry_valor_venda, 0.75)\n",
    "\n",
    "print(f'A média é {media}')\n",
    "print (f'A mediana é {mediana}')\n",
    "print (f'Primeiro quartil é (Q1){q1}')\n",
    "print (f'Segundo quartil é (Q2){q2}')\n",
    "print (f'Terceiro quartil é (Q3){q3}')"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 10,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Valor de Venda</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ANGRA DOS REIS</td>\n",
       "      <td>6.470086</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>MACAE</td>\n",
       "      <td>6.224548</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>TRES RIOS</td>\n",
       "      <td>6.206138</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>BARRA DO PIRAI</td>\n",
       "      <td>6.168793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>SAQUAREMA</td>\n",
       "      <td>6.070452</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>ITAPERUNA</td>\n",
       "      <td>6.069675</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>PETROPOLIS</td>\n",
       "      <td>6.064262</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Municipio  Valor de Venda\n",
       "0   ANGRA DOS REIS        6.470086\n",
       "10           MACAE        6.224548\n",
       "24       TRES RIOS        6.206138\n",
       "2   BARRA DO PIRAI        6.168793\n",
       "23       SAQUAREMA        6.070452\n",
       "9        ITAPERUNA        6.069675\n",
       "16      PETROPOLIS        6.064262"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "munic_acima_q3 = media_munc_rj.loc[media_munc_rj['Valor de Venda'] > q3]\n",
    "munic_acima_q3"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 11,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Regiao - Sigla</th>\n",
       "      <th>Estado - Sigla</th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Revenda</th>\n",
       "      <th>CNPJ da Revenda</th>\n",
       "      <th>Nome da Rua</th>\n",
       "      <th>Numero Rua</th>\n",
       "      <th>Complemento</th>\n",
       "      <th>Bairro</th>\n",
       "      <th>Cep</th>\n",
       "      <th>Produto</th>\n",
       "      <th>Data da Coleta</th>\n",
       "      <th>Valor de Venda</th>\n",
       "      <th>Valor de Compra</th>\n",
       "      <th>Unidade de Medida</th>\n",
       "      <th>Bandeira</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1000</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.</td>\n",
       "      <td>07.877.289/0001-70</td>\n",
       "      <td>RUA VOLUNTARIOS DA PATRIA</td>\n",
       "      <td>308</td>\n",
       "      <td>NaN</td>\n",
       "      <td>BOTAFOGO</td>\n",
       "      <td>22270-010</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1004</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO DE GASOLINA GASOAL LTDA</td>\n",
       "      <td>05.159.154/0001-44</td>\n",
       "      <td>RUA VINTE E QUATRO DE MAIO</td>\n",
       "      <td>871</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ENGENHO NOVO</td>\n",
       "      <td>20950-091</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>BRANCA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO CATEDRAL LTDA</td>\n",
       "      <td>27.838.044/0001-41</td>\n",
       "      <td>AVENIDA MEM DE SA</td>\n",
       "      <td>55</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>20230-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1013</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO PALACIO GUANABARA LTDA</td>\n",
       "      <td>04.816.108/0001-08</td>\n",
       "      <td>RUA PINHEIRO MACHADO</td>\n",
       "      <td>83</td>\n",
       "      <td>83/FUNDOS</td>\n",
       "      <td>LARANJEIRAS</td>\n",
       "      <td>22231-090</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,69</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1018</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO ATERRO DO FLAMENGO LTDA</td>\n",
       "      <td>01.309.199/0001-05</td>\n",
       "      <td>AVENIDA INFANTO DOM HENRIQUE</td>\n",
       "      <td>S/N</td>\n",
       "      <td>NaN</td>\n",
       "      <td>FLAMENGO</td>\n",
       "      <td>20021-140</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>5,70</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418188</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO DE GASOLINA CIDADE DE DEUS LTDA</td>\n",
       "      <td>11.333.439/0001-52</td>\n",
       "      <td>ESTRADA DO GABINAL</td>\n",
       "      <td>1955</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CIDADE DE DEUS</td>\n",
       "      <td>22763-153</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,19</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>IPIRANGA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418246</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>BARRA GAS COMERCIO E SERVICOS LTDA</td>\n",
       "      <td>11.513.372/0001-38</td>\n",
       "      <td>AVENIDA AYRTON SENNA</td>\n",
       "      <td>9201</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JACAREPAGUA</td>\n",
       "      <td>22775-004</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>IPIRANGA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418257</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>CENTRO DE ABASTECIMENTO CHESSED LTDA</td>\n",
       "      <td>11.054.754/0001-40</td>\n",
       "      <td>AVENIDA AMARO CAVALCANTI</td>\n",
       "      <td>2554</td>\n",
       "      <td>A 2562                    LOJA</td>\n",
       "      <td>ENGENHO DE DENTRO</td>\n",
       "      <td>20735-042</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>BRANCA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418842</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO LUAR DA RIO SANTOS II LTDA</td>\n",
       "      <td>11.217.808/0001-41</td>\n",
       "      <td>ESTRADA DO GUANDU ESQ.C/  BR 101</td>\n",
       "      <td>SN</td>\n",
       "      <td>KM    388 AREA REM III    LOTE  210 SENTIDO RJ</td>\n",
       "      <td>SANTA CRUZ</td>\n",
       "      <td>23560-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>419214</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO LUAR DA RIO SANTOS I LTDA</td>\n",
       "      <td>11.103.499/0001-89</td>\n",
       "      <td>ESTRADA DO GANDU ESQ C/BR101</td>\n",
       "      <td>SN</td>\n",
       "      <td>KM    388 AREA REM I      LOTE  209 SENTIDO ANGRA</td>\n",
       "      <td>SANTA CRUZ</td>\n",
       "      <td>23560-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,39</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1799 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       Regiao - Sigla Estado - Sigla       Municipio  \\\n",
       "1000               SE             RJ  RIO DE JANEIRO   \n",
       "1004               SE             RJ  RIO DE JANEIRO   \n",
       "1009               SE             RJ  RIO DE JANEIRO   \n",
       "1013               SE             RJ  RIO DE JANEIRO   \n",
       "1018               SE             RJ  RIO DE JANEIRO   \n",
       "...               ...            ...             ...   \n",
       "418188             SE             RJ  RIO DE JANEIRO   \n",
       "418246             SE             RJ  RIO DE JANEIRO   \n",
       "418257             SE             RJ  RIO DE JANEIRO   \n",
       "418842             SE             RJ  RIO DE JANEIRO   \n",
       "419214             SE             RJ  RIO DE JANEIRO   \n",
       "\n",
       "                                       Revenda      CNPJ da Revenda  \\\n",
       "1000    POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.   07.877.289/0001-70   \n",
       "1004             POSTO DE GASOLINA GASOAL LTDA   05.159.154/0001-44   \n",
       "1009                       POSTO CATEDRAL LTDA   27.838.044/0001-41   \n",
       "1013              POSTO PALACIO GUANABARA LTDA   04.816.108/0001-08   \n",
       "1018        AUTO POSTO ATERRO DO FLAMENGO LTDA   01.309.199/0001-05   \n",
       "...                                        ...                  ...   \n",
       "418188   POSTO DE GASOLINA CIDADE DE DEUS LTDA   11.333.439/0001-52   \n",
       "418246      BARRA GAS COMERCIO E SERVICOS LTDA   11.513.372/0001-38   \n",
       "418257    CENTRO DE ABASTECIMENTO CHESSED LTDA   11.054.754/0001-40   \n",
       "418842   AUTO POSTO LUAR DA RIO SANTOS II LTDA   11.217.808/0001-41   \n",
       "419214    AUTO POSTO LUAR DA RIO SANTOS I LTDA   11.103.499/0001-89   \n",
       "\n",
       "                             Nome da Rua Numero Rua  \\\n",
       "1000           RUA VOLUNTARIOS DA PATRIA        308   \n",
       "1004          RUA VINTE E QUATRO DE MAIO        871   \n",
       "1009                   AVENIDA MEM DE SA         55   \n",
       "1013                RUA PINHEIRO MACHADO         83   \n",
       "1018        AVENIDA INFANTO DOM HENRIQUE        S/N   \n",
       "...                                  ...        ...   \n",
       "418188                ESTRADA DO GABINAL       1955   \n",
       "418246              AVENIDA AYRTON SENNA       9201   \n",
       "418257          AVENIDA AMARO CAVALCANTI       2554   \n",
       "418842  ESTRADA DO GUANDU ESQ.C/  BR 101         SN   \n",
       "419214      ESTRADA DO GANDU ESQ C/BR101         SN   \n",
       "\n",
       "                                              Complemento             Bairro  \\\n",
       "1000                                                  NaN           BOTAFOGO   \n",
       "1004                                                  NaN       ENGENHO NOVO   \n",
       "1009                                                  NaN             CENTRO   \n",
       "1013                                            83/FUNDOS        LARANJEIRAS   \n",
       "1018                                                  NaN           FLAMENGO   \n",
       "...                                                   ...                ...   \n",
       "418188                                                NaN     CIDADE DE DEUS   \n",
       "418246                                                NaN        JACAREPAGUA   \n",
       "418257                     A 2562                    LOJA  ENGENHO DE DENTRO   \n",
       "418842     KM    388 AREA REM III    LOTE  210 SENTIDO RJ         SANTA CRUZ   \n",
       "419214  KM    388 AREA REM I      LOTE  209 SENTIDO ANGRA         SANTA CRUZ   \n",
       "\n",
       "              Cep Produto Data da Coleta Valor de Venda  Valor de Compra  \\\n",
       "1000    22270-010  ETANOL     02/01/2025           4,49              NaN   \n",
       "1004    20950-091  ETANOL     02/01/2025           4,09              NaN   \n",
       "1009    20230-150  ETANOL     02/01/2025           4,49              NaN   \n",
       "1013    22231-090  ETANOL     02/01/2025           4,69              NaN   \n",
       "1018    20021-140  ETANOL     02/01/2025           5,70              NaN   \n",
       "...           ...     ...            ...            ...              ...   \n",
       "418188  22763-153  ETANOL     30/06/2025           4,19              NaN   \n",
       "418246  22775-004  ETANOL     30/06/2025           4,29              NaN   \n",
       "418257  20735-042  ETANOL     30/06/2025           4,09              NaN   \n",
       "418842  23560-150  ETANOL     30/06/2025           4,29              NaN   \n",
       "419214  23560-150  ETANOL     30/06/2025           4,39              NaN   \n",
       "\n",
       "       Unidade de Medida  Bandeira  \n",
       "1000          R$ / litro    RAIZEN  \n",
       "1004          R$ / litro    BRANCA  \n",
       "1009          R$ / litro    RAIZEN  \n",
       "1013          R$ / litro    RAIZEN  \n",
       "1018          R$ / litro     VIBRA  \n",
       "...                  ...       ...  \n",
       "418188        R$ / litro  IPIRANGA  \n",
       "418246        R$ / litro  IPIRANGA  \n",
       "418257        R$ / litro    BRANCA  \n",
       "418842        R$ / litro    RAIZEN  \n",
       "419214        R$ / litro    RAIZEN  \n",
       "\n",
       "[1799 rows x 16 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_rj_etanol = df_anp.loc [(df_anp['Municipio'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]\n",
    "df_rj_etanol"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 12,
=======
   "execution_count": null,
>>>>>>> 66f57d3d82b48b0db6b0dfddd0c45c1804e8d6b2
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Regiao - Sigla</th>\n",
       "      <th>Estado - Sigla</th>\n",
       "      <th>Municipio</th>\n",
       "      <th>Revenda</th>\n",
       "      <th>CNPJ da Revenda</th>\n",
       "      <th>Nome da Rua</th>\n",
       "      <th>Numero Rua</th>\n",
       "      <th>Complemento</th>\n",
       "      <th>Bairro</th>\n",
       "      <th>Cep</th>\n",
       "      <th>Produto</th>\n",
       "      <th>Data da Coleta</th>\n",
       "      <th>Valor de Venda</th>\n",
       "      <th>Valor de Compra</th>\n",
       "      <th>Unidade de Medida</th>\n",
       "      <th>Bandeira</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1000</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.</td>\n",
       "      <td>07.877.289/0001-70</td>\n",
       "      <td>RUA VOLUNTARIOS DA PATRIA</td>\n",
       "      <td>308</td>\n",
       "      <td>NaN</td>\n",
       "      <td>BOTAFOGO</td>\n",
       "      <td>22270-010</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1004</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO DE GASOLINA GASOAL LTDA</td>\n",
       "      <td>05.159.154/0001-44</td>\n",
       "      <td>RUA VINTE E QUATRO DE MAIO</td>\n",
       "      <td>871</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ENGENHO NOVO</td>\n",
       "      <td>20950-091</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>BRANCA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO CATEDRAL LTDA</td>\n",
       "      <td>27.838.044/0001-41</td>\n",
       "      <td>AVENIDA MEM DE SA</td>\n",
       "      <td>55</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CENTRO</td>\n",
       "      <td>20230-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,49</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1013</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO PALACIO GUANABARA LTDA</td>\n",
       "      <td>04.816.108/0001-08</td>\n",
       "      <td>RUA PINHEIRO MACHADO</td>\n",
       "      <td>83</td>\n",
       "      <td>83/FUNDOS</td>\n",
       "      <td>LARANJEIRAS</td>\n",
       "      <td>22231-090</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>4,69</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1018</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO ATERRO DO FLAMENGO LTDA</td>\n",
       "      <td>01.309.199/0001-05</td>\n",
       "      <td>AVENIDA INFANTO DOM HENRIQUE</td>\n",
       "      <td>S/N</td>\n",
       "      <td>NaN</td>\n",
       "      <td>FLAMENGO</td>\n",
       "      <td>20021-140</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>02/01/2025</td>\n",
       "      <td>5,70</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>VIBRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418188</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>POSTO DE GASOLINA CIDADE DE DEUS LTDA</td>\n",
       "      <td>11.333.439/0001-52</td>\n",
       "      <td>ESTRADA DO GABINAL</td>\n",
       "      <td>1955</td>\n",
       "      <td>NaN</td>\n",
       "      <td>CIDADE DE DEUS</td>\n",
       "      <td>22763-153</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,19</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>IPIRANGA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418246</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>BARRA GAS COMERCIO E SERVICOS LTDA</td>\n",
       "      <td>11.513.372/0001-38</td>\n",
       "      <td>AVENIDA AYRTON SENNA</td>\n",
       "      <td>9201</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JACAREPAGUA</td>\n",
       "      <td>22775-004</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>IPIRANGA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418257</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>CENTRO DE ABASTECIMENTO CHESSED LTDA</td>\n",
       "      <td>11.054.754/0001-40</td>\n",
       "      <td>AVENIDA AMARO CAVALCANTI</td>\n",
       "      <td>2554</td>\n",
       "      <td>A 2562                    LOJA</td>\n",
       "      <td>ENGENHO DE DENTRO</td>\n",
       "      <td>20735-042</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>BRANCA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418842</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO LUAR DA RIO SANTOS II LTDA</td>\n",
       "      <td>11.217.808/0001-41</td>\n",
       "      <td>ESTRADA DO GUANDU ESQ.C/  BR 101</td>\n",
       "      <td>SN</td>\n",
       "      <td>KM    388 AREA REM III    LOTE  210 SENTIDO RJ</td>\n",
       "      <td>SANTA CRUZ</td>\n",
       "      <td>23560-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>419214</th>\n",
       "      <td>SE</td>\n",
       "      <td>RJ</td>\n",
       "      <td>RIO DE JANEIRO</td>\n",
       "      <td>AUTO POSTO LUAR DA RIO SANTOS I LTDA</td>\n",
       "      <td>11.103.499/0001-89</td>\n",
       "      <td>ESTRADA DO GANDU ESQ C/BR101</td>\n",
       "      <td>SN</td>\n",
       "      <td>KM    388 AREA REM I      LOTE  209 SENTIDO ANGRA</td>\n",
       "      <td>SANTA CRUZ</td>\n",
       "      <td>23560-150</td>\n",
       "      <td>ETANOL</td>\n",
       "      <td>30/06/2025</td>\n",
       "      <td>4,39</td>\n",
       "      <td>NaN</td>\n",
       "      <td>R$ / litro</td>\n",
       "      <td>RAIZEN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1799 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       Regiao - Sigla Estado - Sigla       Municipio  \\\n",
       "1000               SE             RJ  RIO DE JANEIRO   \n",
       "1004               SE             RJ  RIO DE JANEIRO   \n",
       "1009               SE             RJ  RIO DE JANEIRO   \n",
       "1013               SE             RJ  RIO DE JANEIRO   \n",
       "1018               SE             RJ  RIO DE JANEIRO   \n",
       "...               ...            ...             ...   \n",
       "418188             SE             RJ  RIO DE JANEIRO   \n",
       "418246             SE             RJ  RIO DE JANEIRO   \n",
       "418257             SE             RJ  RIO DE JANEIRO   \n",
       "418842             SE             RJ  RIO DE JANEIRO   \n",
       "419214             SE             RJ  RIO DE JANEIRO   \n",
       "\n",
       "                                       Revenda      CNPJ da Revenda  \\\n",
       "1000    POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.   07.877.289/0001-70   \n",
       "1004             POSTO DE GASOLINA GASOAL LTDA   05.159.154/0001-44   \n",
       "1009                       POSTO CATEDRAL LTDA   27.838.044/0001-41   \n",
       "1013              POSTO PALACIO GUANABARA LTDA   04.816.108/0001-08   \n",
       "1018        AUTO POSTO ATERRO DO FLAMENGO LTDA   01.309.199/0001-05   \n",
       "...                                        ...                  ...   \n",
       "418188   POSTO DE GASOLINA CIDADE DE DEUS LTDA   11.333.439/0001-52   \n",
       "418246      BARRA GAS COMERCIO E SERVICOS LTDA   11.513.372/0001-38   \n",
       "418257    CENTRO DE ABASTECIMENTO CHESSED LTDA   11.054.754/0001-40   \n",
       "418842   AUTO POSTO LUAR DA RIO SANTOS II LTDA   11.217.808/0001-41   \n",
       "419214    AUTO POSTO LUAR DA RIO SANTOS I LTDA   11.103.499/0001-89   \n",
       "\n",
       "                             Nome da Rua Numero Rua  \\\n",
       "1000           RUA VOLUNTARIOS DA PATRIA        308   \n",
       "1004          RUA VINTE E QUATRO DE MAIO        871   \n",
       "1009                   AVENIDA MEM DE SA         55   \n",
       "1013                RUA PINHEIRO MACHADO         83   \n",
       "1018        AVENIDA INFANTO DOM HENRIQUE        S/N   \n",
       "...                                  ...        ...   \n",
       "418188                ESTRADA DO GABINAL       1955   \n",
       "418246              AVENIDA AYRTON SENNA       9201   \n",
       "418257          AVENIDA AMARO CAVALCANTI       2554   \n",
       "418842  ESTRADA DO GUANDU ESQ.C/  BR 101         SN   \n",
       "419214      ESTRADA DO GANDU ESQ C/BR101         SN   \n",
       "\n",
       "                                              Complemento             Bairro  \\\n",
       "1000                                                  NaN           BOTAFOGO   \n",
       "1004                                                  NaN       ENGENHO NOVO   \n",
       "1009                                                  NaN             CENTRO   \n",
       "1013                                            83/FUNDOS        LARANJEIRAS   \n",
       "1018                                                  NaN           FLAMENGO   \n",
       "...                                                   ...                ...   \n",
       "418188                                                NaN     CIDADE DE DEUS   \n",
       "418246                                                NaN        JACAREPAGUA   \n",
       "418257                     A 2562                    LOJA  ENGENHO DE DENTRO   \n",
       "418842     KM    388 AREA REM III    LOTE  210 SENTIDO RJ         SANTA CRUZ   \n",
       "419214  KM    388 AREA REM I      LOTE  209 SENTIDO ANGRA         SANTA CRUZ   \n",
       "\n",
       "              Cep Produto Data da Coleta Valor de Venda  Valor de Compra  \\\n",
       "1000    22270-010  ETANOL     02/01/2025           4,49              NaN   \n",
       "1004    20950-091  ETANOL     02/01/2025           4,09              NaN   \n",
       "1009    20230-150  ETANOL     02/01/2025           4,49              NaN   \n",
       "1013    22231-090  ETANOL     02/01/2025           4,69              NaN   \n",
       "1018    20021-140  ETANOL     02/01/2025           5,70              NaN   \n",
       "...           ...     ...            ...            ...              ...   \n",
       "418188  22763-153  ETANOL     30/06/2025           4,19              NaN   \n",
       "418246  22775-004  ETANOL     30/06/2025           4,29              NaN   \n",
       "418257  20735-042  ETANOL     30/06/2025           4,09              NaN   \n",
       "418842  23560-150  ETANOL     30/06/2025           4,29              NaN   \n",
       "419214  23560-150  ETANOL     30/06/2025           4,39              NaN   \n",
       "\n",
       "       Unidade de Medida  Bandeira  \n",
       "1000          R$ / litro    RAIZEN  \n",
       "1004          R$ / litro    BRANCA  \n",
       "1009          R$ / litro    RAIZEN  \n",
       "1013          R$ / litro    RAIZEN  \n",
       "1018          R$ / litro     VIBRA  \n",
       "...                  ...       ...  \n",
       "418188        R$ / litro  IPIRANGA  \n",
       "418246        R$ / litro  IPIRANGA  \n",
       "418257        R$ / litro    BRANCA  \n",
       "418842        R$ / litro    RAIZEN  \n",
       "419214        R$ / litro    RAIZEN  \n",
       "\n",
       "[1799 rows x 16 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_rj_etanol = df_anp.loc [(df_anp['Municipio'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]\n",
    "df_rj_etanol"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\luiz.gutemberg\\AppData\\Local\\Temp\\ipykernel_13724\\282234156.py:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df_rj_etanol['Valor de Venda'] = df_rj_etanol['Valor de Venda'].str.replace(',', '.').astype(float)\n"
     ]
    }
   ],
   "source": [
    "df_rj_etanol['Valor de Venda'] = df_rj_etanol['Valor de Venda'].str.replace(',', '.').astype(float)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Bairro</th>\n",
       "      <th>Valor de Venda</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>FLAMENGO</td>\n",
       "      <td>5.700000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>JARDIM BOTANICO</td>\n",
       "      <td>5.137619</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>VARGEM PEQUENA</td>\n",
       "      <td>5.035000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>LAGOA</td>\n",
       "      <td>4.906667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>GAVEA</td>\n",
       "      <td>4.890000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>LARANJEIRAS</td>\n",
       "      <td>4.860833</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>LEBLON</td>\n",
       "      <td>4.823333</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>ITANHANGA</td>\n",
       "      <td>4.802000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>VASCO DA GAMA</td>\n",
       "      <td>4.795556</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>JARDIM  GUANABARA-ILHA DO GOVERNADOR</td>\n",
       "      <td>4.790000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>GLORIA</td>\n",
       "      <td>4.790000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>JARDIM CARIOCA</td>\n",
       "      <td>4.780000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>SANTISSIMO</td>\n",
       "      <td>4.779286</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>JACAREPAGUÁ</td>\n",
       "      <td>4.778235</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>BOTAFOGO</td>\n",
       "      <td>4.745814</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>BENFICA</td>\n",
       "      <td>4.743846</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>PILARES</td>\n",
       "      <td>4.715000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>RECREIO DOS BANDEIR</td>\n",
       "      <td>4.715000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>CENTRO</td>\n",
       "      <td>4.702500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>ESTÁCIO</td>\n",
       "      <td>4.690000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>ILHA DO FUNDÃO</td>\n",
       "      <td>4.690000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>BONSUCESSO</td>\n",
       "      <td>4.690000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>53</th>\n",
       "      <td>VISTA ALEGRE</td>\n",
       "      <td>4.661429</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>RECREIO DOS BANDEIRANTES</td>\n",
       "      <td>4.661111</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>CAJU</td>\n",
       "      <td>4.646250</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>TIJUCA</td>\n",
       "      <td>4.639091</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>SANTA CRUZ</td>\n",
       "      <td>4.638090</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>DEL CASTILHO</td>\n",
       "      <td>4.628873</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>BARRA DA TIJUCA</td>\n",
       "      <td>4.612042</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>BANGU</td>\n",
       "      <td>4.572857</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>ESTACIO</td>\n",
       "      <td>4.554000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>TAQUARA</td>\n",
       "      <td>4.546400</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ANCHIETA</td>\n",
       "      <td>4.544286</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>PENHA</td>\n",
       "      <td>4.519333</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>JACAREPAGUA</td>\n",
       "      <td>4.505407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>GUADALUPE</td>\n",
       "      <td>4.502500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>PACIENCIA</td>\n",
       "      <td>4.490000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>SÃO CRISTÓVÃO</td>\n",
       "      <td>4.478462</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>PECHINCHA</td>\n",
       "      <td>4.474490</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>CAMPO GRANDE</td>\n",
       "      <td>4.474079</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>SAO CRISTOVAO</td>\n",
       "      <td>4.459730</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>VILA DA PENHA</td>\n",
       "      <td>4.412222</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>ENGENHO NOVO</td>\n",
       "      <td>4.392424</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>RAMOS</td>\n",
       "      <td>4.379583</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>FREGUESIA (JACAREPAGUA)</td>\n",
       "      <td>4.334444</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>PADRE MIGUEL</td>\n",
       "      <td>4.315000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>CATUMBI</td>\n",
       "      <td>4.307391</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>OLARIA</td>\n",
       "      <td>4.305200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>ENGENHO DE DENTRO</td>\n",
       "      <td>4.236923</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>BRAZ DE PINA</td>\n",
       "      <td>4.205000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>RIO COMPRIDO</td>\n",
       "      <td>4.205000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>PRACA SECA</td>\n",
       "      <td>4.190000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>CIDADE DE DEUS</td>\n",
       "      <td>4.173333</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>ROCHA MIRANDA</td>\n",
       "      <td>4.170000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                  Bairro  Valor de Venda\n",
       "17                              FLAMENGO        5.700000\n",
       "27                       JARDIM BOTANICO        5.137619\n",
       "50                        VARGEM PEQUENA        5.035000\n",
       "29                                 LAGOA        4.906667\n",
       "19                                 GAVEA        4.890000\n",
       "30                           LARANJEIRAS        4.860833\n",
       "31                                LEBLON        4.823333\n",
       "23                             ITANHANGA        4.802000\n",
       "51                         VASCO DA GAMA        4.795556\n",
       "26  JARDIM  GUANABARA-ILHA DO GOVERNADOR        4.790000\n",
       "20                                GLORIA        4.790000\n",
       "28                        JARDIM CARIOCA        4.780000\n",
       "45                            SANTISSIMO        4.779286\n",
       "25                           JACAREPAGUÁ        4.778235\n",
       "5                               BOTAFOGO        4.745814\n",
       "3                                BENFICA        4.743846\n",
       "37                               PILARES        4.715000\n",
       "40                   RECREIO DOS BANDEIR        4.715000\n",
       "10                                CENTRO        4.702500\n",
       "16                               ESTÁCIO        4.690000\n",
       "22                        ILHA DO FUNDÃO        4.690000\n",
       "4                             BONSUCESSO        4.690000\n",
       "53                          VISTA ALEGRE        4.661429\n",
       "41              RECREIO DOS BANDEIRANTES        4.661111\n",
       "7                                   CAJU        4.646250\n",
       "49                                TIJUCA        4.639091\n",
       "44                            SANTA CRUZ        4.638090\n",
       "12                          DEL CASTILHO        4.628873\n",
       "2                        BARRA DA TIJUCA        4.612042\n",
       "1                                  BANGU        4.572857\n",
       "15                               ESTACIO        4.554000\n",
       "48                               TAQUARA        4.546400\n",
       "0                               ANCHIETA        4.544286\n",
       "36                                 PENHA        4.519333\n",
       "24                           JACAREPAGUA        4.505407\n",
       "21                             GUADALUPE        4.502500\n",
       "33                             PACIENCIA        4.490000\n",
       "47                         SÃO CRISTÓVÃO        4.478462\n",
       "35                             PECHINCHA        4.474490\n",
       "8                           CAMPO GRANDE        4.474079\n",
       "46                         SAO CRISTOVAO        4.459730\n",
       "52                         VILA DA PENHA        4.412222\n",
       "14                          ENGENHO NOVO        4.392424\n",
       "39                                 RAMOS        4.379583\n",
       "18               FREGUESIA (JACAREPAGUA)        4.334444\n",
       "34                          PADRE MIGUEL        4.315000\n",
       "9                                CATUMBI        4.307391\n",
       "32                                OLARIA        4.305200\n",
       "13                     ENGENHO DE DENTRO        4.236923\n",
       "6                           BRAZ DE PINA        4.205000\n",
       "42                          RIO COMPRIDO        4.205000\n",
       "38                            PRACA SECA        4.190000\n",
       "11                        CIDADE DE DEUS        4.173333\n",
       "43                         ROCHA MIRANDA        4.170000"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "bairro_etanol = df_rj_etanol.groupby('Bairro') ['Valor de Venda'].mean().reset_index()\n",
    "bairro_etanol = bairro_etanol.sort_values (by = 'Valor de Venda', ascending = False)\n",
    "bairro_etanol"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
